```ts
export const daytimeFilenames = [
  '🐿️ shipping from the treetops in the morning light',
  '🐿️ happily tinkering in the waking woods',
  '🐿️ getting things done in the sunny grove',
  '🐿️ stacking commits like acorns beneath the morning sun',
  '🐿️ steadily debugging as the mist clears',
  '🐿️ eagerly deploying in the quiet hours after dawn',
  '🐿️ pushing commits beneath a bright morning sky',
  '🐿️ cozily crafting beneath the old oak',
  '🐿️ cooking up something new in the sunlit canopy',
  '🐿️ patiently building as the forest wakes',
  '🐿️ working through the backlog in the morning sunshine',
  '🐿️ playfully hacking in a bright green meadow',
  '🐿️ happily refactoring among the sunlit trees',
  '🐿️ building something new before breakfast',
  '🐿️ merging changes as sunlight filters through the leaves',
  '🐿️ patching bugs in the early morning light',
  '🐿️ cheerfully coding beneath the warm daytime sun',
  '🐿️ steadily building among the bright green branches',
  '🐿️ scripting away high in the sunlit canopy',
  '🐿️ cozily compiling beneath the rustling leaves',
  '🐿️ shipping while the morning is still young',
  '🐿️ committing code in a meadow full of daylight',
  '🐿️ eagerly building in the warm and sunny grove',
  '🐿️ contentedly coding beneath the oak on a bright day',
];

export const nighttimeFilenames = [
  '🦔 shipping from the burrow in the evening glow',
  '🦔 quietly tinkering beneath the oak after nightfall',
  '🦔 getting things done in the moonlit grove',
  '🦔 stacking commits like mushrooms beneath the stars',
  '🦔 steadily debugging among the moonlit moss',
  '🦔 quietly deploying beneath the evening moon',
  '🦔 pushing commits deep into the quiet night',
  '🦔 cozily crafting in the brambles after dark',
  '🦔 cooking up something new beneath the moon',
  '🦔 patiently building while the woods sleep',
  '🦔 working through the backlog in the evening calm',
  '🦔 playfully hacking among the mushrooms after dark',
  '🦔 quietly refactoring in the cool moonlit moss',
  '🦔 building something new well past midnight',
  '🦔 merging changes beneath a sky full of stars',
  '🦔 patching bugs in the middle of the night',
  '🦔 coding beneath the stars after dark',
  '🦔 steadily building in the soft glow of moonlight',
  '🦔 scripting away among the evening brambles',
  '🦔 cozily compiling beneath a quiet moon',
  '🦔 shipping while the rest of the woods sleeps',
  '🦔 committing code in the grove beneath the stars',
  '🦔 quietly building beneath the midnight sky',
  '🦔 contentedly coding among the moss by moonlight',
];
```
