/**
 * GitHub Linguist groups file languages under these names in repository statistics.
 * Derived from github-linguist/linguist (MIT), languages.yml blob
 * https://api.github.com/repos/github-linguist/linguist/git/blobs/1f72a41cd8f04e170b79d95aea99a4bf1df54458
 */
export const languageGroups: ReadonlyMap<string, string> = new Map([
  ['Alpine Abuild', 'Shell'],
  ['Apollo Guidance Computer', 'Assembly'],
  ['BibTeX', 'TeX'],
  ['Bison', 'Yacc'],
  ['Bluespec BH', 'Bluespec'],
  ['C2hs Haskell', 'Haskell'],
  ['Cairo', 'Cairo'],
  ['Cairo Zero', 'Cairo'],
  ['CameLIGO', 'LigoLANG'],
  ['ColdFusion CFC', 'ColdFusion'],
  ['Cylc', 'INI'],
  ['ECLiPSe', 'Prolog'],
  ['Easybuild', 'Python'],
  ['Ecere Projects', 'JavaScript'],
  ['Ecmarkup', 'HTML'],
  ['EditorConfig', 'INI'],
  ['Elvish Transcript', 'Elvish'],
  ['Filterscript', 'RenderScript'],
  ['Fortran', 'Fortran'],
  ['Fortran Free Form', 'Fortran'],
  ['Gentoo Ebuild', 'Shell'],
  ['Gentoo Eclass', 'Shell'],
  ['Git Config', 'INI'],
  ['Glimmer JS', 'JavaScript'],
  ['Glimmer TS', 'TypeScript'],
  ['Gradle Kotlin DSL', 'Gradle'],
  ['Groovy Server Pages', 'Groovy'],
  ['HTML+ECR', 'HTML'],
  ['HTML+EEX', 'HTML'],
  ['HTML+ERB', 'HTML'],
  ['HTML+PHP', 'HTML'],
  ['HTML+Razor', 'HTML'],
  ['Isabelle ROOT', 'Isabelle'],
  ['JFlex', 'Lex'],
  ['JSON with Comments', 'JSON'],
  ['Java Server Pages', 'Java'],
  ['Java Template Engine', 'Java'],
  ['JavaScript+ERB', 'JavaScript'],
  ['Jison', 'Yacc'],
  ['Jison Lex', 'Lex'],
  ['Julia REPL', 'Julia'],
  ['Lean 4', 'Lean'],
  ['LigoLANG', 'LigoLANG'],
  ['Literate Agda', 'Agda'],
  ['Literate CoffeeScript', 'CoffeeScript'],
  ['Literate Haskell', 'Haskell'],
  ['M4Sugar', 'M4'],
  ['MUF', 'Forth'],
  ['Maven POM', 'XML'],
  ['Motorola 68K Assembly', 'Assembly'],
  ['NPM Config', 'INI'],
  ['NumPy', 'Python'],
  ['OASv2-json', 'OpenAPI Specification v2'],
  ['OASv2-yaml', 'OpenAPI Specification v2'],
  ['OASv3-json', 'OpenAPI Specification v3'],
  ['OASv3-yaml', 'OpenAPI Specification v3'],
  ['OpenCL', 'C'],
  ['OpenRC runscript', 'Shell'],
  ['Parrot Assembly', 'Parrot'],
  ['Parrot Internal Representation', 'Parrot'],
  ['Pic', 'Roff'],
  ['PostCSS', 'CSS'],
  ['Python console', 'Python'],
  ['Python traceback', 'Python'],
  ['RBS', 'Ruby'],
  ['Readline Config', 'INI'],
  ['ReasonLIGO', 'LigoLANG'],
  ['Roff Manpage', 'Roff'],
  ['SSH Config', 'INI'],
  ['STON', 'Smalltalk'],
  ['Simple File Verification', 'Checksums'],
  ['Snakemake', 'Python'],
  ['TSX', 'TypeScript'],
  ['Tcsh', 'Shell'],
  ['Terraform Template', 'HCL'],
  ['Unified Parallel C', 'C'],
  ['Unix Assembly', 'Assembly'],
  ['Wget Config', 'INI'],
  ['X BitMap', 'C'],
  ['X PixMap', 'C'],
  ['XML Property List', 'XML'],
  ['cURL Config', 'INI'],
  ['desktop', 'INI'],
  ['fish', 'Shell'],
  ['nanorc', 'INI'],
]);
