name: Update README

on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update README
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: ${{ vars.TIMEZONE }}
